### ISSUE TITLE
vivo x7 unlock failed

### ISSUE THREAD

**Issue by gxitm** [Naveen3Singh/vivo_fastboot#2]
I run vivo_bsp unlock or bbk unlock failed on my phone vivo x7(Android7.1.1)

fastboot.exe vivo_bsp unlock_vivo
...
FAILED (remote: check Signature Fail)
finished. total time: 0.009s

fastboot.exe bbk unlock_vivo
...
FAILED (remote: unclock fail.)
finished. total time: 0.002s

**Comment by Naveen3Singh** [comment]
I think it's not working on new phones. 
You have to wait till April to unlock bootloader. 
Yes,  I know how to do that.

**Comment by zihan0721** [comment]
thanks
